apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: farm2
  labels:
    app: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: huangyuan2000/fastapi-demo:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: TOKEN_SECRET
              name: fastapi-secret
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_DEFAULT_REGION
              name: fastapi-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: fastapi-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: fastapi-secret
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: DB_URL
              name: fastapi-secret
        envFrom:
        - configMapRef:
            name: env-config    
        ports:
        - containerPort: 8000




